Feature/popularity sort
ialiev685/project-filmoteka pull request #25
Opened 2021-07-11 22:18 UTC by ABoklogov

Пока сделал запрос по популярности фильмов за неделю и за день. При запросе по слову, это меню убирается, Потом надо будет сделать появление этого меню при базовой загрузке.

2021-07-12 10:15 UTC, ialiev685 requested changes
в файле movieSearch.js тоже подправь рендер через файл renderFilms.js.

2021-07-12 10:15 UTC, ialiev685 commented on src/js/popularity-sort/render-popularity-sort.js
> +import cardForm from '../../hbs/cardForm.hbs';
есть файл renderFilms.js, который рендерит с проверкой(жанры, год....)

2021-07-12 10:15 UTC, ialiev685 commented on src/js/popularity-sort/render-popularity-sort.js
> +        renderFilmsCards(fatch);
есть файл renderFilms.js, который рендерит с проверкой(жанры, год....)

2021-07-12 10:15 UTC, ialiev685 commented on src/js/popularity-sort/render-popularity-sort.js
> +   refs.filmList.insertAdjacentHTML('beforeend', cardForm(films));
есть файл renderFilms.js, который рендерит с проверкой(жанры, год....)

2021-07-12 18:53 UTC, ABoklogov commented
> Пока сделал запрос по популярности фильмов за неделю и за день. При запросе по слову, это меню убирается, Потом надо будет сделать появление этого меню при базовой загрузке.

Сделал начальную загрузку фильмов из локал сторадж. Но не пойму откуда идет второй запрос. Я когда начал это все делать, изначально так и было - 2 запроса, надеюсь, это исправили.

2021-07-13 19:56 UTC, ialiev685 approved these changes

2021-07-13 20:48 UTC, ialiev685 requested changes
Сливай main в свою ветку, много конфликтов. Потом сделай новый пул.

2021-07-16 08:41 UTC, ialiev685 approved these changes

2021-07-16 08:41 UTC, merged